### ISSUE TITLE
After run kselftest.py in Rhel8.1 with Avocado(version:77.0), it shows " CANCEL: Fail to install glibc-static required for this test", which makes the result FAIL

### ISSUE THREAD

**Issue by Gene-Lo** [avocado-framework-tests/avocado-misc-tests#1631]
【Test Result】
After run kselftest.py in Rhel8.1 with Avocado(version:77.0), it shows " CANCEL: Fail to install glibc-static required for this test", which makes the result FAIL. SOL-log is like below:

(1/6) kselftest.py:kselftest.test;vm-distro-b755: CANCEL: Fail to install glibc-static required for this test. (9.67 s)
(2/6) kselftest.py:kselftest.test;vm-upstream-fa5d: CANCEL: Fail to install glibc-static required for this test. (9.77 s)
(3/6) kselftest.py:kselftest.test;power-distro-962b: CANCEL: Fail to install glibc-static required for this test. (9.63 s)
(4/6) kselftest.py:kselftest.test;power-upstream-b645: CANCEL: Fail to install glibc-static required for this test. (9.74 s)
(5/6) kselftest.py:kselftest.test;mem_plug-distro-65c5: CANCEL: Fail to install glibc-static required for this test. (9.69 s)
(6/6) kselftest.py:kselftest.test;mem_plug-upstream-9527: CANCEL: Fail to install glibc-static required for this test. (9.73 s)
RESULTS    : PASS 0 | ERROR 0 | FAIL 0 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 6

However, we can't install "glibc-static" in Rhel8.1 so far. Please check if Rhel8.1 supports "glibc-static" and the test of kselftest.py.

【Expect Result】
After run kselftest.py, it should show PASS. 

【Test Steps】
Run kselftest.py via cmd "avocado run kselftest.py -m kselftest.py.data/list.yaml"

【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.5.1.el8_1.ppc64le

[FW configuration]
BMC: op940.00.mih-5-0-g86f9791c2
PNOR: OP9-v2.4-4.37-prod 

[HW configuration]
CPU DD2.3 20core *2
Hynix (HMA82GR7CJR4N-VKT3/F) 16G *32
Seagate Jaguar 400GB *1
PSU ACBEL 2000w *2

【Test log】: job-log & Manual-Test-log
[Test log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4507298/Test.log.zip)

**Comment by harish-24** [comment]
@Gene-Lo I am sure CRB repo of RHEL 8.1 has this package required for the test. Please check and let know the details.

**Comment by Gene-Lo** [comment]
@harish-24 
We finally installed glibc-static via below cmd:
$subscription-manager repos --enable=codeready-builder-for-rhel-8-ppc64le-rpms
$yum list --showduplicates glibc-static
$yum install glibc-static

However, after we re-test kselftest.py via cmd "avocado run kselftest.py -m kselftest.py.data/kselftest.yaml", it shows "ERROR: [Errno 2] No such file or directory" and other errors.

《SOL-log》
(1/6) kselftest.py:kselftest.test;vm-distro-b755: ERROR: [Errno 2] No such file or directory: '' (35.88 s)
(2/6) kselftest.py:kselftest.test;vm-upstream-fa5d: ERROR: Command 'make -C vm run_tests' failed.\nstdout: b"make: Entering dih8det5r/avocado_job_lq78x0a8/2-kselftest.py_kselftest.test_vm-upstream-fa5d/linux-master/tools/testing/selftests/vm'\nmake --no -C ../.... (808.32 s)
(3/6) kselftest.py:kselftest.test;power-distro-962b: ERROR: [Errno 2] No such file or directory: '' (44.20 s)
(4/6) kselftest.py:kselftest.test;power-upstream-b645: FAIL: Testcase failed during selftests (790.93 s)
(5/6) kselftest.py:kselftest.test;mem_plug-distro-65c5: ERROR: [Errno 2] No such file or directory: '' (181.23 s)
(6/6) kselftest.py:kselftest.test;mem_plug-upstream-9527: PASS (67.67 s)
RESULTS    : PASS 1 | ERROR 4 | FAIL 1 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

《job-log》
L0604 INFO | Running 'rpm -i /var/tmp/avocado_software_managerh7legjms/kernel-4.18.0-147.8.1.el8_1.src.rpm'
L0436 DEBUG| [stderr] warning: user mockbuild does not exist - using root
L0436 DEBUG| [stderr] warning: group mockbuild does not exist - using root
L0436 DEBUG| [stderr] warning: user mockbuild does not exist - using root
L0436 DEBUG| [stderr] warning: group mockbuild does not exist - using root
L0436 DEBUG| [stderr] warning: user mockbuild does not exist - using root
L0436 DEBUG| [stderr] warning: group mockbuild does not exist - using root
(…SKIP…)
L0604 INFO | Running 'yum-builddep -y --tolerant kernel'
L0436 DEBUG| [stdout] Updating Subscription Management repositories.
L0436 DEBUG| [stderr] usage: yum-builddep builddep [-c [config file]] [-q] [-v] [--version]
L0436 DEBUG| [stderr]                              [--installroot [path]] [--nodocs] [--noplugins]
L0436 DEBUG| [stderr]                              [--enableplugin [plugin]]
L0436 DEBUG| [stderr]                              [--disableplugin [plugin]]
L0436 DEBUG| [stderr]                              [--releasever RELEASEVER] [--setopt SETOPTS]
L0436 DEBUG| [stderr]                              [--skip-broken] [-h] [--allowerasing]
L0436 DEBUG| [stderr]                              [-b | --nobest] [-C] [-R [minutes]]
L0436 DEBUG| [stderr]                              [-d [debug level]] [--debugsolver]
L0436 DEBUG| [stderr]                              [--showduplicates] [-e ERRORLEVEL] [--obsoletes]
L0436 DEBUG| [stderr]                              [--rpmverbosity [debug level name]] [-y]
L0436 DEBUG| [stderr]                              [--assumeno] [--enablerepo [repo]]
L0436 DEBUG| [stderr]                              [--disablerepo [repo] | --repo [repo]]
L0436 DEBUG| [stderr]                              [--enable | --disable] [-x [package]]
L0436 DEBUG| [stderr]                              [--disableexcludes [repo]]
L0436 DEBUG| [stderr]                              [--repofrompath [repo,path]] [--noautoremove]
L0436 DEBUG| [stderr]                              [--nogpgcheck] [--color COLOR] [--refresh] [-4]
L0436 DEBUG| [stderr]                              [-6] [--destdir DESTDIR] [--downloadonly]
L0436 DEBUG| [stderr]                              [--comment COMMENT] [--bugfix] [--enhancement]
L0436 DEBUG| [stderr]                              [--newpackage] [--security] [--advisory ADVISORY]
L0436 DEBUG| [stderr]                              [--bz BUGZILLA] [--cve CVES]
L0436 DEBUG| [stderr]                              [--sec-severity {Critical,Important,Moderate,Low}]
L0436 DEBUG| [stderr]                              [--forcearch ARCH] [-D 'MACRO EXPR']
L0436 DEBUG| [stderr]                              [--spec | --srpm]
L0436 DEBUG| [stderr]                              package [package ...]
L0436 DEBUG| [stderr] yum-builddep builddep: error: unrecognized arguments: --tolerant
L0686 INFO | Command 'yum-builddep -y --tolerant kernel' finished with 2 after 7.4214653968811035s
L0661 ERROR| Command 'yum-builddep -y --tolerant kernel' failed.


【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.5.1.el8_1.ppc64le

[FW configuration]
BMC: op940.15.mih-1-0-g7983355f4
PNOR: OP9-v2.4-4.40-prod

[HW configuration]
CPU DD2.3 16 core *2
DIMM(Micron_ MTA18ASF2G72PZ-2G9E1_DDR4,16GB)*32
Seagate Jaguar 400GB *2
PSU ACBEL 2000w *2


【Test log】: job-log & Manual-Test-log
[20200421_kselftest_JOB-LOG & Manual-Test-Log.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4537760/20200421_kselftest_JOB-LOG.Manual-Test-Log.zip)

**Comment by harish-24** [comment]
@Gene-Lo which is same as https://github.com/avocado-framework-tests/avocado-misc-tests/issues/1584.. I see @PraveenPenguin is working on this (assuming from assigning to himself). 

@PraveenPenguin Please update on the same. If its not being worked upon I will be able to take it up.

**Comment by harish-24** [comment]
@Gene-Lo If there are no other issues, we can close this and pursue in that issue.

**Comment by PraveenPenguin** [comment]
@harish-24 yes please as not able get time to work on

**Comment by harish-24** [comment]
@Gene-Lo  https://github.com/avocado-framework/avocado/pull/3750 and https://github.com/avocado-framework/avocado/pull/3751 should fix the issues

**Comment by Gene-Lo** [comment]
@harish-24 @PraveenPenguin 
OK. Many thanks for your kindly help!!

**Comment by Gene-Lo** [comment]
Dear @harish-24 
Excuse me that after we run kselftest.py in Rhel8.1 with Avocado(version:79.0), it still shows FAIL.
Please kindly support us. Many thanks!!

《SOL log》
(1/6) kselftest.py:kselftest.test;vm-distro-b755: FAIL: Testcase failed during selftests (26647.54 s)
(2/6) kselftest.py:kselftest.test;vm-upstream-fa5d: FAIL: Testcase failed during selftests (809.12 s)
(3/6) kselftest.py:kselftest.test;power-distro-962b: FAIL: Testcase failed during selftests (985.10 s)
(4/6) kselftest.py:kselftest.test;power-upstream-b645: FAIL: Testcase failed during selftests (873.60 s)
(5/6) kselftest.py:kselftest.test;mem_plug-distro-65c5: PASS (342.58 s)
(6/6) kselftest.py:kselftest.test;mem_plug-upstream-9527: PASS (56.80 s)
RESULTS    : PASS 2 | ERROR 0 | FAIL 4 | SKIP 0 | WARN 0 | INTERRUPT 0 | CANCEL 0

《job log》- Take some logs for example:
【Item 1】
L0607 INFO | Running 'rpm -i /var/tmp/avocado_software_managervrt85jgb/kernel-4.18.0-193.1.2.el8_2.src.rpm'
L0439 DEBUG| [stderr] warning: user mockbuild does not exist - using root
L0439 DEBUG| [stderr] warning: group mockbuild does not exist - using root
L0439 DEBUG| [stderr] warning: user mockbuild does not exist - using root
L0439 DEBUG| [stderr] warning: group mockbuild does not exist - using root
L0439 DEBUG| [stderr] warning: user mockbuild does not exist - using root
→Our OS version is Rhel8.1, but it catches “kernel-4.18.0-193.1.2.el8_2.src.rpm”

【Item 2】
L0607 INFO | Running 'make summary=1 -C vm run_tests'
L0439 DEBUG| [stdout] make: Entering directory '/var/tmp/avocado_w32lcmrd/avocado_job_wxrxdw7w/2-kselftest.py_kselftest.test_vm-upstream-fa5d/linux-master/tools/testing/selftests/vm'
L0439 DEBUG| [stdout] make --no-builtin-rules ARCH=powerpc -C ../../../.. headers_install
L0439 DEBUG| [stdout] make[1]: Entering directory '/var/tmp/avocado_w32lcmrd/avocado_job_wxrxdw7w/2-kselftest.py_kselftest.test_vm-upstream-fa5d/linux-master/tools/testing/selftests/vm'
L0439 DEBUG| [stderr] make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
L0439 DEBUG| [stdout]   INSTALL ./usr/include
L0439 DEBUG| [stdout] make[1]: Leaving directory '/var/tmp/avocado_w32lcmrd/avocado_job_wxrxdw7w/2-kselftest.py_kselftest.test_vm-upstream-fa5d/linux-master'
L0439 DEBUG| [stdout] TAP version 13
L0439 DEBUG| [stdout] 1..1
L0439 DEBUG| [stdout] # selftests: vm: run_vmtests
L0439 DEBUG| [stdout] #
L0689 INFO | Command 'make summary=1 -C vm run_tests' finished with 0 after 68.58725666999817s
L0439 DEBUG| [stdout] not ok 1 selftests: vm: run_vmtests # TIMEOUT
L0439 DEBUG| [stdout] make: Leaving directory '/var/tmp/avocado_w32lcmrd/avocado_job_wxrxdw7w/2-kselftest.py_kselftest.test_vm-upstream-fa5d/linux-master/tools/testing/selftests/vm'
L0049 INFO | Testcase failed. Log from debug: not ok 1 selftests: vm: run_vmtests # TIMEOUT

【Item 3】
L0607 INFO | Running 'rpm -i /var/tmp/avocado_software_managerklz7llfq/kernel-4.18.0-193.1.2.el8_2.src.rpm'
L0439 DEBUG| [stderr] warning: user mockbuild does not exist - using root
L0439 DEBUG| [stderr] warning: group mockbuild does not exist - using root
L0439 DEBUG| [stderr] warning: user mockbuild does not exist - using root
L0439 DEBUG| [stderr] warning: group mockbuild does not exist - using root
L0439 DEBUG| [stderr] warning: user mockbuild does not exist - using root
→Our OS version is Rhel8.1, but it catches “kernel-4.18.0-193.1.2.el8_2.src.rpm”

【Item 4】
L0607 INFO | Running 'rpm -i /var/tmp/avocado_software_manager6hyc96sy/kernel-4.18.0-193.1.2.el8_2.src.rpm'
L0439 DEBUG| [stderr] warning: user mockbuild does not exist - using root
L0439 DEBUG| [stderr] warning: group mockbuild does not exist - using root
L0439 DEBUG| [stderr] warning: user mockbuild does not exist - using root
→Our OS version is Rhel8.1, but it catches “kernel-4.18.0-193.1.2.el8_2.src.rpm”


《Test log》
[20200601-kselftest-JOB_LOG.zip](https://github.com/avocado-framework-tests/avocado-misc-tests/files/4715558/20200601-kselftest-JOB_LOG.zip)


【Expect Result】
After run kselftest.py, it should show PASS.


【Test Steps】
Run kselftest via below cmd:
$ subscription-manager repos --enable=codeready-builder-for-rhel-8-ppc64le-rpms
$ yum install glibc-static
$ avocado run kselftest.py -m kselftest.py.data/kselftest.yaml


【Configuration】
[Rhel8.1 Kernel]
4.18.0-147.8.1.el8_1.ppc64le

[FW config]
BMC: op940.15.mih-2-0-ga72988e66
PNOR: OP9-v2.4-4.49-prod

[HW config]
CPU DD2.3 20core *2
Micron (MTA18ASF2G72PZ-2G9E1) 16G *4
Seagate Jaguar 400GB *1
PSU ACBEL 2000w *1
Broadcom (LSI) MegaRAID 9361-8i SAS3 Controller w/ 8 internal ports *1 @ slot5
Samsung PM1643 (SSD; 3840GB; 2.5"; SAS; 12Gb/s; 1 DWPD; NonSED) *2

**Comment by harish-24** [comment]
@Gene-Lo Those are test failures and needs to be debugged at the OS level. Not related to any test case issue. As for the warning you have pasted, it is harmless and is not related to the test failures.

**Comment by Gene-Lo** [comment]
@harish-24 Thanks for you feedback!!
@nasastry Could you kindly double check the issue?
